# Generated by Django 3.2.6 on 2022-04-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookdetails',
            name='published_on',
            field=models.DateField(),
        ),
    ]
